networks:
  mcp-network:
    driver: bridge

services:
  milvus:
    container_name: milvus
    hostname: milvus
    image: milvusdb/milvus:v2.5.11
    security_opt:
      - "seccomp:unconfined"
    environment:
      ETCD_USE_EMBED: true
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      ETCD_CONFIG_PATH: /milvus/configs/embedEtcd.yaml
      COMMON_STORAGETYPE: local
    volumes:
      - data:/var/lib/milvus
      - ./conf/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./conf/user.yaml:/milvus/configs/user.yaml
      - ./conf/milvus.yaml:/milvus/configs/milvus.yaml
    command: milvus run standalone
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    # ports:
    #   - 19530:19530
    #   - 9091:9091    
    #   - 2379:2379

  mcp-server:
    container_name: mcp-server
    hostname: mcp-server
    build: ./mcp-server
    environment:
      MILVUS_URI: "http://milvus:19530"
      MILVUS_TOKEN: "root:Milvus"
      MILVUS_DB: "mcp_db"
      MILVUS_COLLECTION: "full_text_search"
    ports:
      - 3000:3000
    networks:
      - mcp-network
    depends_on:
      - milvus
volumes:
  data:
